services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-net
    env_file:
      - .env
    environment:
      DB_HOST : db

  db:
    image: postgres:14-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel-net

volumes:
  db_data:

networks:
  laravel-net:
    driver: bridge
